### ISSUE TITLE
有什么方法让工程中的redis disable掉？？？

### ISSUE THREAD

**Issue by luxury515** [geekidea/spring-boot-plus#37]
我刚 git clone  该工程。然后执行发现需要redis，因为本人macOS 还未安装。
有什么方法让工程中的redis disable掉？？？

2019-08-28 18:29:43.119  WARN 9722 [     parallel-3] o.s.b.a.r.RedisReactiveHealthIndicator   [89] : Redis health check failed

org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379
	at org.springframework.data.redis.connection.lettuce.LettucePoolingConnectionProvider.getConnection(LettucePoolingConnectionProvider.java:87)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:1104)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getConnection(LettuceConnectionFactory.java:1085)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getSharedReactiveConnection(LettuceConnectionFactory.java:876)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getReactiveConnection(LettuceConnectionFactory.java:377)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getReactiveConnection(LettuceConnectionFactory.java:91)
	at reactor.core.publisher.MonoSupplier.call(MonoSupplier.java:85)
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:225)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:50)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:27)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
	at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:235)
	at io.lettuce.core.RedisClient.connect(RedisClient.java:204)
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.lambda$getConnection$1(StandaloneConnectionProvider.java:113)
	at java.util.Optional.orElseGet(Optional.java:267)

**Comment by springboot-plus** [comment]
项目中很多地方都使用了redis，如果项目中确实不需要redis
- 先删除pom.xml中的data-redis依赖
- 删除redis相关配置，改造redis依赖引用代码

- 建议在mac上安装redis server
[https://redis.io/topics/quickstart](https://redis.io/topics/quickstart)

**Comment by luxury515** [comment]
crud -> mysql 这个已经知道了，
能告诉我一下，redis 用在哪个功能上呢？

**Comment by springboot-plus** [comment]
查询频率高的，也可以Redis缓存，提供查询效率
权限拦截过滤，用户绑定的角色权限，可以缓存在Redis
登陆信息，缓存在Redis
字典类型数据，可缓存在Redis中
验证码短信过期/Redis高并发锁等等
这些功能有的已经用到，有的在后面的功能中也将会用到
Redis将会是spring-boot-plus项目中的必要依赖
而且Redis在公司实际项目中，应用非常广泛，谢谢。

**Comment by luxury515** [comment]
redis 刚安装完毕，
追问一下，基于本项目，需要额外的去配置redis吗？
都有哪些 ？

**Comment by springboot-plus** [comment]
装好redis，启动服务，不用其它配置，直接使用
如果修改了redis配置，如端口，密码等，需自行配置
